services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
      - DB_URL=${DB_URL}
      - RESEND_KEY=${RESEND_KEY}
      - RESEND_EMAIL=${RESEND_EMAIL}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    volumes:
      - .:/app
    develop:
      watch:
        - action: sync
          path: ./app.py
          target: /app/app.py
        - action: rebuild
          path: ./requirements.txt
