services:
  web:
    build: .
    ports:
      - "80:5000"
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
      - DB_URL=${DB_URL}
      - SENDGRID_KEY=${SENDGRID_KEY}
      - SENDGRID_EMAIL=${SENDGRID_EMAIL}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    volumes:
      - .:/app
    develop:
      watch:
        - action: sync
          path: ./app.py
          target: /app/app.py
        - action: rebuild
          path: ./requirements.txt
