name: Deploy to Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.4
        env:
          DB_URL: ${{ secrets.DB_URL }}
          FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          envs: DB_URL,FLASK_DEBUG,SENDGRID_KEY,SENDGRID_EMAIL,FLASK_SECRET_KEY
          script: |
            cd code-connect/
            git pull origin main
            sudo touch sqlite.db
            sudo chmod 666 sqlite.db
            sudo chmod 777 .
            docker compose build
            docker compose up -d
            docker image prune -f
